name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # Skip CI on draft PRs
  skip-draft:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - name: Skip draft PR
        run: echo "Skipping CI for draft PR"

  ci:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run format check
        run: npm run format -- --check

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test -- --coverage --watchAll=false

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        if: matrix.node-version == '20.x'
        with:
          fail_ci_if_error: false

      - name: Build library
        run: npm run build

      - name: Check build artifacts
        run: |
          test -f dist/cjs/index.js || exit 1
          test -f dist/esm/index.js || exit 1
          test -f dist/types.d.ts || exit 1
          echo "✅ All build artifacts generated successfully"

      - name: Test package installation
        run: |
          npm pack
          npm install -g ./b3-libraryui-*.tgz
          echo "✅ Package can be installed successfully"
