name: PR Checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft != true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=moderate

      - name: Check for outdated dependencies
        run: npm outdated || true

      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          disallowScopes: |
            release

      - name: Check bundle size
        run: |
          npm run build
          BUNDLE_SIZE=$(stat -c%s "dist/esm/index.js")
          echo "Bundle size: $BUNDLE_SIZE bytes"
          if [ $BUNDLE_SIZE -gt 100000 ]; then
            echo "⚠️ Bundle size is larger than 100KB"
          else
            echo "✅ Bundle size is acceptable"
          fi

      - name: Check for TODO comments
        run: |
          TODO_COUNT=$(grep -r "TODO\|FIXME\|XXX" src/ --exclude-dir=node_modules || true)
          if [ ! -z "$TODO_COUNT" ]; then
            echo "⚠️ TODO/FIXME comments found:"
            echo "$TODO_COUNT"
          else
            echo "✅ No TODO/FIXME comments found"
          fi
